project:
  type: website
  render:
    - "index.qmd"
    - "slides/*qmd"
    - "!CODE_OF_CONDUCT.md"
  output-dir: docs

website:
  title: "Methods in longitudinal dementia research workshop"
  description: "This workshop provides an introduction to oblique and causal random forests. Oblique random forests are used for dementia risk prediction and causal random forests are used to identify heterogeneity in the association between APOE4 and dementia."
  open-graph: true
  twitter-card: false
  site-url: https://bcjaeger.github.io/melodem-apoe4-het/
  repo-url: https://github.com/bcjaeger/melodem-apoe4-het
  repo-actions: [edit, issue]
  favicon: "favicon.ico"

  navbar:
    background: "white"
    pinned: true
    logo: melodem-logo.png
    right:
      - text: Learn more
        menu:
          - href: https://docs.ropensci.org/aorsf/
            text: "Oblique random forests using aorsf"
          - href: https://grf-labs.github.io/grf/
            text: "causal random forests (and more) using grf"

format:
  html:
    theme: cosmo
    css: styles.css

fig-format: svg
